export interface AddonItem {
  id: string;
  name: string;
  category: "speech" | "education" | "media" | "system" | "tools";
  categoryLabel: string;
  hasVietnamese: boolean;
  inStore: boolean; // true: Có trên Cửa hàng Add-on NVDA chính thức; false: Cộng đồng độc lập (chưa có trên Store)
  origin: "vietnam" | "spain" | "russia" | "international";
  originLabel: string;
  description: string;
  author: string;
  authorGithub: string | null;
  repoUrl: string | null;
  license: string;
  shortcuts?: string;
  downloadUrl: string;
  testedVersion: string;
  version?: string;
  updatedAt?: string; // ISO 8601 string
  updatedAtVN?: string; // dd/mm/yyyy
}

export const addonsList: AddonItem[] = [
  // --- VIỆT NAM & ĐỘC LẬP ---
  {
    id: "radiotv",
    name: "RadioTV",
    category: "media",
    categoryLabel: "Đa phương tiện & Giải trí",
    hasVietnamese: true,
    inStore: false,
    origin: "vietnam",
    originLabel: "Việt Nam",
    description: "Tiện ích nghe đài phát thanh VOV, VOH, đài tỉnh và xem truyền hình tiếp cận 100% bằng phím bấm, không quảng cáo.",
    author: "Võ Duy Khánh",
    authorGithub: "https://github.com/voduykhanhmata-ctrl",
    repoUrl: "https://github.com/voduykhanhmata-ctrl/radiotv",
    license: "GNU GPLv2",
    shortcuts: "Mũi tên lên/xuống để chọn đài, Enter để phát, F để yêu thích",
    downloadUrl: "https://github.com/voduykhanhmata-ctrl/radiotv/releases/download/v0.1.0/RadioTV-0.1.0.nvda-addon",
    testedVersion: "NVDA 2024.1+",
  },
  {
    id: "nvda-network-optimizer",
    name: "NVDA Network Optimizer",
    category: "system",
    categoryLabel: "Hệ thống & Mạng",
    hasVietnamese: true,
    inStore: false,
    origin: "vietnam",
    originLabel: "Việt Nam",
    description: "Chẩn đoán mạng, đo độ trễ ping và chuyển đổi máy chủ DNS sạch, an toàn (Cloudflare, Google, Quad9) chỉ với 1 phím bấm.",
    author: "Võ Duy Khánh",
    authorGithub: "https://github.com/voduykhanhmata-ctrl",
    repoUrl: "https://github.com/voduykhanhmata-ctrl/NVDA-Network-Optimizer",
    license: "GNU GPLv2",
    shortcuts: "Mở menu NVDA -> Network Optimizer",
    downloadUrl: "https://github.com/voduykhanhmata-ctrl/NVDA-Network-Optimizer/releases",
    testedVersion: "NVDA 2024.1+",
  },
  {
    id: "google-tts-nvda",
    name: "Google TTS for NVDA (WASM)",
    category: "speech",
    categoryLabel: "Giọng đọc & Ngôn ngữ",
    hasVietnamese: true,
    inStore: false,
    origin: "vietnam",
    originLabel: "Việt Nam",
    description: "Giọng đọc Google tiếng Việt tự nhiên, truyền cảm, ngắt nghỉ câu chuẩn xác và chạy ngoại tuyến 100% không cần kết nối mạng.",
    author: "Nguyễn Anh Đức, Đào Đức Trung, Phạm Hùng Vương",
    authorGithub: "https://github.com/nguyenanhduc09",
    repoUrl: "https://github.com/nguyenanhduc09/Google-TTS-For-NVDA",
    license: "GNU GPLv3",
    shortcuts: "NVDA + Ctrl + S để chọn bộ đọc Google TTS",
    downloadUrl: "https://github.com/nguyenanhduc09/Google-TTS-For-NVDA/releases",
    testedVersion: "NVDA 2023.1 - 2024.x",
  },
  {
    id: "saomai-vn-speech",
    name: "Sao Mai Voice (VnSpeech)",
    category: "speech",
    categoryLabel: "Giọng đọc & Ngôn ngữ",
    hasVietnamese: true,
    inStore: false,
    origin: "vietnam",
    originLabel: "Việt Nam",
    description: "Bộ giọng đọc tiếng Việt truyền thống quen thuộc (Minh Du) được đóng gói cho NVDA bởi Trung tâm Sao Mai vì người khiếm thị.",
    author: "Trung tâm Vì người mù Sao Mai",
    authorGithub: "https://github.com/saomaicenter",
    repoUrl: "https://saomaicenter.org",
    license: "Freeware / Bản quyền Sao Mai",
    shortcuts: "NVDA + Ctrl + S để chọn bộ tổng hợp",
    downloadUrl: "https://saomaicenter.org/vi/phan-mem/nvda",
    testedVersion: "NVDA 2020 - 2024",
  },

  // --- CỬA HÀNG CHÍNH THỨC & CÓ TIẾNG VIỆT ---
  {
    id: "dual-voice",
    name: "Dual Voice",
    category: "speech",
    categoryLabel: "Giọng đọc & Ngôn ngữ",
    hasVietnamese: true,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế (Có tiếng Việt)",
    description: "Tự động đổi giọng đọc khi đọc văn bản pha trộn tiếng Anh và tiếng Việt: từ tiếng Việt đọc giọng Việt, từ tiếng Anh đọc giọng Anh mượt mà.",
    author: "Mahmood Taghavi",
    authorGithub: "https://github.com/mahmood-taghavi",
    repoUrl: "https://github.com/mahmood-taghavi/dual_voice",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Ctrl + V để chỉnh giọng phụ tiếng Anh",
    downloadUrl: "https://addons.nvaccess.org/addons/dual_voice/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "resource-monitor",
    name: "Resource Monitor (Giám sát tài nguyên)",
    category: "system",
    categoryLabel: "Hệ thống & Mạng",
    hasVietnamese: true,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế (Bản dịch Việt)",
    description: "Đọc nhanh thông số phần cứng máy tính: % dung lượng RAM còn trống, tải CPU, dung lượng ổ đĩa và % pin laptop còn lại.",
    author: "Joseph Lee & Cộng đồng NVDA",
    authorGithub: "https://github.com/josephsl",
    repoUrl: "https://github.com/josephsl/resourcemonitor",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Shift + E để đọc RAM & CPU; NVDA + Shift + 1 để đọc Pin",
    downloadUrl: "https://addons.nvaccess.org/addons/resourceMonitor/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "clock",
    name: "Clock (Đồng hồ & Báo thức)",
    category: "tools",
    categoryLabel: "Công cụ & Tiện ích",
    hasVietnamese: true,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế (Bản dịch Việt)",
    description: "Tiện ích đồng hồ nâng cao: điểm chuông từng giờ như đồng hồ quả lắc, bấm giờ thể thao, hẹn giờ tắt máy và báo thức bằng âm thanh.",
    author: "Hrvoje Katic",
    authorGithub: "https://github.com/hkatic",
    repoUrl: "https://github.com/hkatic/clock",
    license: "GNU GPLv2",
    shortcuts: "NVDA + F12 (1 lần đọc giờ, 2 lần đọc ngày, 3 lần đọc tuần)",
    downloadUrl: "https://addons.nvaccess.org/addons/clock/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "golden-cursor",
    name: "Golden Cursor (Chuột vàng)",
    category: "tools",
    categoryLabel: "Công cụ & Tiện ích",
    hasVietnamese: true,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế (Bản dịch Việt)",
    description: "Điều khiển và di chuyển con trỏ chuột từng pixel hoặc từng khoảng cách bằng bàn phím số (Numpad) để nhấp vào các nút khó tiếp cận.",
    author: "Salah Atair",
    authorGithub: "https://github.com/salahatair",
    repoUrl: "https://github.com/salahatair/goldenCursor",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Bàn phím số để di chuyển chuột và nhấp chuột trái/phải",
    downloadUrl: "https://addons.nvaccess.org/addons/goldenCursor/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "speech-history",
    name: "Speech History (Lịch sử đọc)",
    category: "speech",
    categoryLabel: "Giọng đọc & Ngôn ngữ",
    hasVietnamese: true,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế (Bản dịch Việt)",
    description: "Xem lại và sao chép vào bộ nhớ tạm những câu nói mà NVDA vừa phát âm, cực kỳ tiện lợi khi lỡ nghe không rõ một thông báo trên màn hình.",
    author: "Tyler Spivey",
    authorGithub: "https://github.com/tspivey",
    repoUrl: "https://github.com/tspivey/speech-history",
    license: "GNU GPLv2",
    shortcuts: "Shift + F11 để nghe câu trước, Shift + F12 để nghe câu sau",
    downloadUrl: "https://addons.nvaccess.org/addons/speechHistory/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "weather-plus",
    name: "Weather Plus (Dự báo thời tiết)",
    category: "tools",
    categoryLabel: "Công cụ & Tiện ích",
    hasVietnamese: true,
    inStore: true,
    origin: "spain",
    originLabel: "Tây Ban Nha (NVDA.es)",
    description: "Xem dự báo thời tiết, nhiệt độ, độ ẩm và tốc độ gió tại các thành phố và tỉnh thành Việt Nam cũng như trên toàn thế giới.",
    author: "Adriano Barbieri & NVDA.es",
    authorGithub: "https://github.com/Adriano-Barbieri",
    repoUrl: "https://github.com/Adriano-Barbieri/Weather-Plus",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Shift + W để nghe thời tiết hiện tại",
    downloadUrl: "https://addons.nvaccess.org/addons/weatherPlus/",
    testedVersion: "NVDA 2024.x",
  },

  // --- CỬA HÀNG CHÍNH THỨC & CÔNG CỤ QUỐC TẾ NỔI BẬT ---
  {
    id: "bluetooth-audio",
    name: "Bluetooth Audio (Chống nuốt tiếng)",
    category: "media",
    categoryLabel: "Đa phương tiện & Giải trí",
    hasVietnamese: false,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế",
    description: "Giữ kết nối tai nghe hoặc loa Bluetooth luôn ở trạng thái thức (active), giải quyết triệt để lỗi bị nuốt mất 1-2 từ đầu tiên khi nghe NVDA.",
    author: "Luke Davis",
    authorGithub: "https://github.com/opensourcesys",
    repoUrl: "https://github.com/opensourcesys/bluetoothaudio",
    license: "GNU GPLv2",
    shortcuts: "Tự động kích hoạt khi cài đặt, không cần phím tắt",
    downloadUrl: "https://addons.nvaccess.org/addons/bluetoothaudio/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "access8math",
    name: "Access8Math (Toán học tiếp cận)",
    category: "education",
    categoryLabel: "Học tập & Văn phòng",
    hasVietnamese: false,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế",
    description: "Tiện ích hàng đầu thế giới giúp người khiếm thị đọc, phân tích và viết các công thức Toán học, Vật lý (MathML, LaTeX) bằng giọng nói và chữ nổi.",
    author: "Ts. Tamas Geczy",
    authorGithub: "https://github.com/Access8Math",
    repoUrl: "https://github.com/Access8Math/Access8Math",
    license: "GNU GPLv2",
    shortcuts: "Mũi tên điều hướng công thức toán, Space để đi vào biểu thức con",
    downloadUrl: "https://addons.nvaccess.org/addons/Access8Math/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "clip-contents-designer",
    name: "Clip Contents Designer",
    category: "tools",
    categoryLabel: "Công cụ & Tiện ích",
    hasVietnamese: false,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế",
    description: "Quản lý sao chép văn bản nâng cao: cho phép nối thêm các đoạn copy tiếp theo vào Clipboard thay vì bị ghi đè, xem trước danh sách copy.",
    author: "Noelia Ruiz Martínez",
    authorGithub: "https://github.com/nvda-addons",
    repoUrl: "https://github.com/nvda-addons/clipContentsDesigner",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Windows + C để nối văn bản copy",
    downloadUrl: "https://addons.nvaccess.org/addons/clipContentsDesigner/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "vlc-accessibility",
    name: "VLC Accessibility",
    category: "media",
    categoryLabel: "Đa phương tiện & Giải trí",
    hasVietnamese: false,
    inStore: true,
    origin: "spain",
    originLabel: "Tây Ban Nha (NVDA.es)",
    description: "Tối ưu hóa trình phát media VLC Player cho người khiếm thị: thông báo thời lượng phim, phụ đề và danh sách bài hát mượt mà.",
    author: "Javier Romañach & NVDA.es",
    authorGithub: "https://github.com/nvdaes",
    repoUrl: "https://github.com/nvdaes/vlc",
    license: "GNU GPLv2",
    shortcuts: "Ctrl + Mũi tên để tua thời gian và đọc số phút đã xem",
    downloadUrl: "https://addons.nvaccess.org/addons/vlc/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "say-current-keyboard-language",
    name: "Say Current Keyboard Language",
    category: "tools",
    categoryLabel: "Công cụ & Tiện ích",
    hasVietnamese: false,
    inStore: true,
    origin: "russia",
    originLabel: "Nga (NVDA.ru)",
    description: "Phát âm thanh ngắn hoặc đọc to ngôn ngữ bàn phím hiện tại mỗi khi bạn nhấn phím Alt+Shift hoặc Ctrl+Shift để đổi bộ gõ (tránh gõ nhầm mật khẩu).",
    author: "Zvuk & NVDA.ru Community",
    authorGithub: "https://github.com/nvdaru",
    repoUrl: "https://github.com/nvdaru/sayCurrentKeyboardLanguage",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Shift + L để đọc ngôn ngữ gõ hiện tại",
    downloadUrl: "https://addons.nvaccess.org/addons/sayCurrentKeyboardLanguage/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "ai-content-describer",
    name: "AI Content Describer",
    category: "education",
    categoryLabel: "Học tập & Văn phòng",
    hasVietnamese: false,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế",
    description: "Tích hợp trí tuệ nhân tạo (AI) mô tả chi tiết nội dung của bất kỳ hình ảnh, biểu đồ, ảnh chụp văn bản nào ngay trên màn hình.",
    author: "Adil Adysh",
    authorGithub: "https://github.com/adil-adysh",
    repoUrl: "https://github.com/adil-adysh/NVDA-AI-assistant",
    license: "MIT",
    shortcuts: "NVDA + Shift + D để mô tả đối tượng đồ họa dưới con trỏ",
    downloadUrl: "https://addons.nvaccess.org/addons/AIContentDescriber/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "instant-translate",
    name: "Instant Translate (Dịch tức thì)",
    category: "education",
    categoryLabel: "Học tập & Văn phòng",
    hasVietnamese: true,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế (Bản dịch Việt)",
    description: "Dịch nhanh đoạn văn bản đang bôi đen hoặc nội dung trong bộ nhớ tạm (Clipboard) sang tiếng Việt hoặc bất kỳ ngôn ngữ nào chỉ bằng 1 phím tắt.",
    author: "Alexy Sadovoi, Beqa Gozalishvili",
    authorGithub: "https://github.com/bertsky",
    repoUrl: "https://github.com/bertsky/instant-translate",
    license: "GNU GPLv2",
    shortcuts: "Shift + NVDA + T để dịch văn bản được chọn",
    downloadUrl: "https://addons.nvaccess.org/addons/instantTranslate/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "read-feeds",
    name: "Read Feeds (Đọc báo tin tức RSS)",
    category: "media",
    categoryLabel: "Đa phương tiện & Giải trí",
    hasVietnamese: false,
    inStore: true,
    origin: "spain",
    originLabel: "Tây Ban Nha (NVDA.es)",
    description: "Đọc tin tức thời sự từ các nguồn RSS báo chí (VnExpress, Tuổi Trẻ, BBC...) ngay trong giao diện văn bản tối giản của NVDA.",
    author: "Noelia Ruiz Martínez & NVDA.es",
    authorGithub: "https://github.com/nvdaes",
    repoUrl: "https://github.com/nvdaes/readFeeds",
    license: "GNU GPLv2",
    shortcuts: "NVDA + Ctrl + Shift + R để mở danh sách tin tức",
    downloadUrl: "https://addons.nvaccess.org/addons/readFeeds/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "obj-location-tones",
    name: "Object Location Tones",
    category: "tools",
    categoryLabel: "Công cụ & Tiện ích",
    hasVietnamese: false,
    inStore: true,
    origin: "international",
    originLabel: "Quốc tế",
    description: "Phát âm thanh cao thấp và âm lượng loa trái/phải để người khiếm thị định vị tọa độ của đối tượng đang focus trên không gian màn hình thực tế.",
    author: "Joseph Lee",
    authorGithub: "https://github.com/josephsl",
    repoUrl: "https://github.com/josephsl/objLocationTones",
    license: "GNU GPLv2",
    shortcuts: "Tự động phát âm thanh khi di chuyển tiêu điểm",
    downloadUrl: "https://addons.nvaccess.org/addons/objLocationTones/",
    testedVersion: "NVDA 2024.x",
  },
  {
    id: "crash-log-viewer",
    name: "Crash Log Viewer (Xem lỗi NVDA)",
    category: "system",
    categoryLabel: "Hệ thống & Mạng",
    hasVietnamese: false,
    inStore: true,
    origin: "russia",
    originLabel: "Nga (NVDA.ru)",
    description: "Tiện ích cho phép xem nhanh và sao chép nhật ký lỗi (log file) khi NVDA gặp sự cố hoặc add-on bị crash mà không phải mở thư mục ẩn AppData.",
    author: "Kostya & NVDA.ru Community",
    authorGithub: "https://github.com/nvdaru",
    repoUrl: "https://github.com/nvdaru/crashLogViewer",
    license: "GNU GPLv2",
    shortcuts: "NVDA + F1 để xem lỗi gần nhất",
    downloadUrl: "https://addons.nvaccess.org/addons/crashLogViewer/",
    testedVersion: "NVDA 2024.x",
  },
];

import storeAddonsJson from "./addons-store.json";

// Hợp nhất dữ liệu tuyển chọn với toàn bộ kho Store (500+ add-on)
// Giữ lại mô tả tiếng Việt và phím tắt chi tiết của các add-on đã được tinh chỉnh
const curatedMap = new Map(addonsList.map((item) => [item.id, item]));
const storeList: AddonItem[] = (storeAddonsJson as AddonItem[]).map((item) => {
  const curated = curatedMap.get(item.id);
  if (curated) {
    return {
      ...curated,
      version: item.version || curated.version,
      updatedAt: item.updatedAt || curated.updatedAt,
      updatedAtVN: item.updatedAtVN || curated.updatedAtVN,
      downloadUrl: item.downloadUrl || curated.downloadUrl,
    };
  }
  return item;
});

// Các add-on tuyển chọn độc lập ngoài Store (RadioTV, Network Optimizer, v.v.)
const externalCurated = addonsList.filter((item) => !item.inStore);

// Gộp chung và SẮP XẾP MỚI CẬP NHẬT LÊN ĐẦU TIÊN (Newest update first)
export const allAddonsList: AddonItem[] = [...externalCurated, ...storeList].sort(
  (a, b) => {
    const timeA = a.updatedAt ? new Date(a.updatedAt).getTime() : 0;
    const timeB = b.updatedAt ? new Date(b.updatedAt).getTime() : 0;
    return timeB - timeA;
  }
);

